### ISSUE TITLE
A way to avoid huge allocations

### ISSUE THREAD

**Issue by niklasf** [image-rs/weezl#10]
Currently the encoder unconditionally makes huge allocations. I assume this is a performance tradeoff.

https://github.com/image-rs/lzw/blob/0d3c809a37574cc84684e02c96c62ef079c926c9/src/encode.rs#L251

Could there be a way to select a different tradeoff, maximum, or maybe something based on the size of the input?

**Comment by 197g** [comment]
Hm, yes. I suppose you could add a method to configure this buffer size or to pass in a borrowed buffer with the lifetime of the state's borrow.

**Comment by niklasf** [comment]
Thank you! Amazing solution.
