### ISSUE TITLE
Rename repository to weezl

### ISSUE THREAD

**Issue by fintelia** [image-rs/weezl#42]
This crate is published under the name `weezl`. It might make sense to rename the repository to match, to avoid possible confusion

**Comment by kornelski** [comment]
If you do, please also make a release that updates the repo url in the crate, so that link between them can be verified.

**Comment by fintelia** [comment]
You can verify the link by observing that https://github.com/image-rs/lzw redirects here now, but I'll publish a new release with the updated URL soon
